### ISSUE TITLE
number padding needs to be looked at

### ISSUE THREAD

**Issue by revelt** [xfix/python-format#7]
hi all,

Consider this attempt to pad by two digits:

```js
var format = require("python-format")
console.log(format('%.2f', 10.2))
// => "%.2f"
```

I would expect a result of `10.20`, not `%.2f`. Is this a bug or is this formatting outside of the scope of this package?

**Comment by xfix** [comment]
@revelt 

This package is for Python 3 formatting (PEP 3101, `format` method or f-strings), not `%` operator formatting.
